name: artattoo
description: Catalogo de tatuajes + reservas (MVP sin Try-On)
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  http: ^1.2.2
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  app_links: ^6.2.0
  image_picker: ^1.0.7
  # Push & notificaciones
  firebase_core:
  firebase_messaging:
  flutter_local_notifications:
  timezone:

flutter:
  uses-material-design: true
  assets:
    - assets/images/image.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
